server:
  port: 14521
  compression:
    enabled: true

spring:
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      # 单个文件的最大上限
      max-file-size: 50MB
      # 单个请求的文件总大小上限
      max-request-size: 50MB

my-config:
  tmp-dir: tmp/
  export-tmp-dir: tmp/export/
  zip-tmp-dir: tmp/zip/
  version: @project.version@